/**
 * @fileoverview Visualization logic for the report.
 */

/**
 * Represents a single Opinion within a Topic.
 * Generated by the 'groupOpinions' function in the processing script.
 * @typedef {Object} Opinion
 * @property {string} text - The text content of the opinion.
 * @property {number} count - The number of quotes assigned to this opinion.
 * @property {string} countFormatted - Comma-separated count string.
 * @property {string} fullID - Unique ID (topicSlug-opinionSlug) used to look up raw quotes.
 * @property {boolean} [viewAllQuotes] - Flag indicating if there are more quotes than the sample.
 * @property {string[]} [sampleQuotes] - A subset of quotes used for previews (if available).
 * @property {string} [topicText] - Parent topic text (injected during frontend flattening).
 * @property {string} [topicId] - Parent topic ID (injected during frontend flattening).
 * @property {number} [_startIndex] - Calculated index for stacked bar visualization.
 * @property {number} [_startCount] - Calculated offset for stacked bar visualization.
 */

/**
 * Represents a high-level Topic containing multiple opinions.
 * @typedef {Object} Topic
 * @property {string} topicID - Slugified ID for the topic.
 * @property {string} text - The display title of the topic.
 * @property {string} [summary] - Summary text for the topic.
 * @property {number} rawQuoteCount - Total sum of quotes across all opinions in this topic.
 * @property {string} quoteCountFormatted - Formatted unique quote count.
 * @property {number} quoteCount - Count of unique representative IDs (participants).
 * @property {number} opinionCount - Number of distinct opinions in this topic.
 * @property {Opinion[]} opinions - Array of opinion objects.
 */

/**
 * Represents the raw Quote object structure stored in quotes.json or payload.
 * @typedef {Object} RawQuote
 * @property {string} id - Matches the 'fullID' of an Opinion.
 * @property {string} quote - The actual text of the user quote.
 */

/**
 * The global data payload injected by the build process.
 * Handles both "inline" (all data in one file) and "static" (fetches quotes separately) modes.
 * @type {{ topics: Topic[], quotes?: RawQuote[], options: { logo: string, overviewChart: string, hasToggle: boolean, sampleQuoteCount: number, topOpinionCount: number, chartColors: string[] } }}
 */
window.PAYLOAD = window.PAYLOAD || {};

/**
 * Default color palette used for visualizing different topics.
 * @constant {string[]}
 */
const PALETTE = window.PAYLOAD.options.chartColors || ["#ccc"];

/**
 * Default number of top opinions to display in the Opinion Chart view.
 * @constant {number}
 */
const NUM_TOP_OPINIONS = window.PAYLOAD.options.topOpinionCount || 10;

/**
 * Overview chart type
 * @constant {string}
 */
const OVERVIEW_CHART_TYPE = window.PAYLOAD.options.overviewChart || "toggle";

/**
 * Renders the primary "Conversation Overview" chart.
 * Displays topics as stacked horizontal bars using SVG.
 * Uses `rawQuoteCount` from the payload to determine bar widths.
 */
function createTopicChart() {
  /** @type {Topic[]} */
  const data = window.PAYLOAD.topics;
  const svgHeight = 32;
  const borderRadius = 4;
  const containerSel = d3.select(`#conversation-overview-chart`);

  const render = () => {
    containerSel.html("");

    const containerNode = containerSel.node();
    const containerWidth = containerNode
      ? containerNode.getBoundingClientRect().width
      : 800;

    // Use rawQuoteCount (sum of all opinion counts) for the scale
    const maxCount = d3.max(data, (d) => d.rawQuoteCount);

    const sortedData = [...data].sort((a, b) =>
      d3.descending(a.rawQuoteCount, b.rawQuoteCount),
    );

    sortedData.forEach((topic, index) => {
      const sortedOpinions = [...topic.opinions].sort((a, b) =>
        d3.descending(a.count, b.count),
      );

      // Calculate cumulative offsets for the stacked bar effect
      let currentAccumulator = 0;
      const processedOpinions = sortedOpinions.map((d, i) => {
        const startVal = currentAccumulator;
        currentAccumulator += d.count;
        return {
          ...d,
          _startIndex: i,
          _startCount: startVal,
        };
      });

      const wrapper = containerSel.append("div").attr("class", "topic-wrapper");

      wrapper
        .append("div")
        .attr("class", "topic-header")
        .html(
          `${topic.text} <span class="topic-meta">(${topic.opinionCount} opinions, ${topic.quoteCountFormatted} total quotes)</span>`,
        );

      const svg = wrapper
        .append("svg")
        .attr("class", "topic-svg")
        .attr("width", "100%")
        .attr("height", svgHeight);

      const gapSize = containerWidth > 600 ? 4 : 2;

      const totalRowGapPixels = Math.max(
        0,
        (processedOpinions.length - 1) * gapSize,
      );

      const topicColor = PALETTE[index % PALETTE.length];
      const hoverColor = d3.color(topicColor).darker(0.8);

      svg
        .selectAll("rect")
        .data(processedOpinions)
        .enter()
        .append("rect")
        .attr("class", "opinion-rect")
        .attr("y", 0)
        .attr("height", svgHeight)
        .attr("x", (d) => {
          const startRatio = d._startCount / maxCount;
          const shiftRight = d._startIndex * gapSize;
          const shiftLeft = startRatio * totalRowGapPixels;

          return `calc(${startRatio * 100}% + ${shiftRight - shiftLeft}px)`;
        })
        .attr("width", (d) => {
          const ratio = d.count / maxCount;
          const shrinkPixels = ratio * totalRowGapPixels;
          return `calc(${ratio * 100}% - ${shrinkPixels}px)`;
        })
        .attr("fill", topicColor)
        .on("mouseover", function () {
          d3.select(this).attr("fill", hoverColor);
        })
        .on("mouseout", function () {
          d3.select(this).attr("fill", topicColor);
        })
        .attr("rx", borderRadius)
        .attr("data-tippy-content", (d) => {
          return `
            <div class="topic-text">${topic.text}</div>
            <div class="quote-count">${d.countFormatted} Quotes</div>
            <div class="opinion-text">${d.text}</div>
          `;
        })
        .style("cursor", "pointer");
    });

    tippy(".opinion-rect", {
      allowHTML: true,
      animation: "fade",
      theme: "light",
      maxWidth: 280,
      delay: 0,
      duration: 0,
      followCursor: true,
    });
  };

  render();

  let resizeTimer;
  window.addEventListener("resize", () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(render, 250);
  });
}

/**
 * Renders the alternative "Top Opinions" view.
 * Flattens the nested data structure (Topic -> Opinions) into a single list
 * to display the most popular opinions regardless of topic.
 */
function createOpinionChart() {
  /** @type {Topic[]} */
  const data = window.PAYLOAD.topics;
  const borderRadius = 4;
  const barHeight = 24;

  const gapSize = 12;
  const containerSel = d3.select(`#conversation-overview-chart`);

  // Flatten opinions and inject parent topic metadata for reference
  const opinions = data
    .map((topic) => {
      return topic.opinions.map((opinion) => ({
        ...opinion,
        topicText: topic.text,
        topicId: topic.topicID,
      }));
    })
    .flat();

  const render = () => {
    containerSel.html("");

    const maxCount = d3.max(opinions, (d) => d.count);

    // Get top X opinions across all topics
    const sortedData = [...opinions]
      .sort((a, b) => d3.descending(a.count, b.count))
      .slice(0, NUM_TOP_OPINIONS);

    // Color map based on topic index to maintain consistency with Topic Chart
    const topicIndexMap = new Map();
    data.forEach((topic, index) => {
      topicIndexMap.set(topic.topicID, index);
    });

    const topicColor = (d) => {
      const topicIndex = topicIndexMap.get(d.topicId) || 0;
      return PALETTE[topicIndex % PALETTE.length];
    };

    const div = containerSel.append("div").attr("class", "opinion-legend");
    data.forEach((topic) => {
      const isInTop = sortedData.some(
        (opinion) => opinion.topicId === topic.topicID,
      );
      if (!isInTop) return;
      const topicIndex = topicIndexMap.get(topic.topicID) || 0;
      const color = PALETTE[topicIndex % PALETTE.length];
      const item = div.append("div").attr("class", "legend-item");
      item
        .append("span")
        .attr("class", "legend-color")
        .style("background-color", color);
      item.append("span").attr("class", "legend-text").text(topic.text);
    });

    const listContainer = containerSel
      .append("div")
      .attr("class", "opinion-list-container")
      .style("width", "100%")
      .style("display", "flex")
      .style("flex-direction", "column");

    const rows = listContainer
      .selectAll(".opinion-row")
      .data(sortedData)
      .enter()
      .append("div")
      .attr("class", "opinion-row")
      .style("margin-bottom", `${gapSize}px`)
      .style("width", "100%");

    rows
      .append("div")
      .attr("class", "opinion-label")
      .text((d) => `${d.text} (${d.countFormatted} quotes)`)
      .style("font-size", "12px")
      .style("color", "#000")
      .style("margin-bottom", "4px")
      .style("line-height", "1.2");

    rows
      .append("div")
      .attr("class", "opinion-bar")
      .style("height", `${barHeight}px`)
      .style("width", (d) => `${(d.count / maxCount) * 100}%`)
      .style("background-color", topicColor)
      .style("border-radius", `${borderRadius}px`)
      .style("cursor", "pointer")
      .style("transition", "background-color 0.2s ease")
      .attr("data-tippy-content", (d) => {
        return `
            <div class="topic-text">${d.topicText}</div>
            <div class="quote-count">${d.countFormatted} Quotes</div>
            <div class="opinion-text">${d.text}</div>
        `;
      })
      .on("mouseover", function () {
        d3.select(this).style(
          "background-color",
          d3.color(topicColor(d3.select(this).data()[0])).darker(0.8),
        );
      })
      .on("mouseout", function () {
        d3.select(this).style("background-color", topicColor);
      });

    tippy(".opinion-bar", {
      allowHTML: true,
      animation: "fade",
      theme: "light",
      maxWidth: 280,
      delay: 0,
      duration: 0,
      followCursor: true,
    });
  };

  render();

  let resizeTimer;
  window.addEventListener("resize", () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(render, 250);
  });
}

/**
 * Renders a Donut Chart for a specific topic.
 * @param {Topic} topicData - The topic data object.
 * @param {number} index - The index of the topic (used for consistent coloring).
 */
function createDonutChart(topicData, index) {
  const containerSel = d3.select(
    `#topic-${topicData.topicID} .donut-chart-content`,
  );

  const gapSizeAngle = 0.025;
  const cornerRadius = 2;
  const thicknessRatio = 0.375;

  const render = () => {
    containerSel.html("");

    const containerNode = containerSel.node();
    const containerWidth = containerNode
      ? containerNode.getBoundingClientRect().width
      : 200;

    const width = containerWidth;
    const height = containerWidth;
    const radius = Math.min(width, height) / 2;

    const sortedOpinions = [...topicData.opinions].sort(
      (a, b) => b.count - a.count,
    );

    const svg = containerSel
      .append("svg")
      .attr("class", "donut-svg")
      .attr("width", width)
      .attr("height", height)
      .append("g")
      .attr("transform", `translate(${width / 2},${height / 2})`);

    const pie = d3
      .pie()
      .value((d) => d.count)
      .sort(null)
      .padAngle(gapSizeAngle);

    const arc = d3
      .arc()
      .innerRadius(radius * (1 - thicknessRatio))
      .outerRadius(radius)
      .cornerRadius(cornerRadius);

    const baseColor = PALETTE[index % PALETTE.length];
    const hoverColor = d3.color(baseColor).darker(0.8);

    svg
      .selectAll("path")
      .data(pie(sortedOpinions))
      .enter()
      .append("path")
      .attr("class", "opinion-segment")
      .attr("d", arc)
      .attr("fill", baseColor)
      .attr("stroke", "none")
      .on("mouseover", function () {
        d3.select(this).attr("fill", hoverColor);
      })
      .on("mouseout", function () {
        d3.select(this).attr("fill", baseColor);
      })
      .style("cursor", "pointer")
      .attr("data-tippy-content", (d) => {
        const opinion = d.data;
        return `
					<div class="topic-text">${topicData.text}</div>
					<div class="quote-count">${opinion.countFormatted} Quotes</div>
					<div class="opinion-text">${opinion.text}</div>
        `;
      });
  };

  const initTooltips = () => {
    tippy(`#topic-${topicData.topicID} .opinion-segment`, {
      allowHTML: true,
      animation: "fade",
      theme: "light",
      maxWidth: 280,
      delay: 0,
      duration: 0,
      followCursor: true,
    });
  };

  render();
  initTooltips();
}

/**
 * Initializes donut charts for all available topics.
 */
function createDonutCharts() {
  const topics = window.PAYLOAD.topics;
  topics.forEach(createDonutChart);
}

/**
 * Populates and opens the modal to display all quotes.
 * @param {Object} params
 * @param {string[]} params.quotes - Array of quote strings.
 * @param {string} params.text - The opinion text used as the header.
 */
function openQuotesModal({ quotes, text }) {
  const modalSel = d3.select("#modal");
  const quoteCount = d3.format(",")(quotes.length);
  modalSel.select(".modal-quote-count").text(`${quoteCount} Quotes`);
  modalSel.select(".modal-opinion").text(text);
  const quotesList = modalSel.select(".modal-quotes");
  quotesList.html("");
  quotes.forEach((quote) => {
    quotesList.append("li").text(quote);
  });
  modalSel.classed("is-open", true);
  quotesList.node().scrollTop = 0;

  // focus on close button for accessibility
  modalSel.select(".button-close").node().focus();
}

/**
 * Loads quote data based on the build strategy.
 * 1. Checks `window.PAYLOAD.quotes` (Inline strategy used in `data-inline.json`).
 * 2. If missing, fetches `quotes.json` (Static strategy used in `data-static.json`).
 *
 * It transforms the flat quote list into a Map keyed by `fullID` (topicSlug-opinionSlug).
 *
 * @returns {Promise<Map<string, string[]>>} Map where Key = fullID, Value = Array of quote strings.
 */
async function loadQuotesData() {
  let quotes = window.PAYLOAD.quotes;
  if (!quotes) {
    try {
      const response = await fetch("quotes.json");
      if (!response.ok) throw new Error(`status: ${response.status}`);
      quotes = await response.json();
    } catch (error) {
      console.error("Could not load quotes.json:", error);
      return new Map();
    }
  }

  // Create lookup map for quick access by opinion.fullID
  const quoteMap = new Map();
  quotes.forEach((q) => {
    if (!quoteMap.has(q.id)) {
      quoteMap.set(q.id, []);
    }
    quoteMap.get(q.id).push(q.quote);
  });
  return quoteMap;
}

/**
 * Initializes the Quotes Modal logic.
 * Binds click events to ".button-quotes" to look up quotes via the Opinion's `fullID`.
 */
async function createQuotesModal() {
  // Flatten opinions to find metadata by ID easily
  const opinions = window.PAYLOAD.topics.map((topic) => topic.opinions).flat();
  const quoteMap = await loadQuotesData();

  // event listeners
  d3.select("#modal .button-close").on("click", () => {
    d3.select("#modal").classed("is-open", false);
  });

  d3.selectAll(".button-quotes").on("click", function () {
    const id = d3.select(this).attr("data-id"); // matches opinion.fullID
    const match = opinions.find((o) => o.fullID === id);
    const text = match?.text || "Unknown Opinion";
    const quotes = quoteMap.get(id);
    openQuotesModal({ quotes, text });
  });

  // keyup event listener for escape key to close modal
  document.addEventListener("keyup", (event) => {
    if (event.key === "Escape") {
      const modalSel = d3.select("#modal");
      if (modalSel.classed("is-open")) modalSel.classed("is-open", false);
    }
  });
}

/**
 * Initializes Share functionality (Copy Link).
 * Generates deep links using the element's ID.
 */
function createShare() {
  const shareSel = d3.select("#share");
  shareSel.select(".button-close-share").on("click", () => {
    shareSel.classed("is-open", false);
  });

  // copy button
  shareSel.select(".button-copy").on("click", function () {
    const input = shareSel.select(".share-url input").node();
    const inputText = input.value;
    navigator.clipboard
      .writeText(inputText)
      .then(() => {
        console.log("copied");
      })
      .catch((err) => {
        console.error("Failed to copy text: ", err);
      });
    d3.select(this).classed("is-copied", true);
    setTimeout(() => {
      d3.select(this).classed("is-copied", false);
    }, 2000);
  });

  d3.selectAll(".button-share").on("click", function () {
    const id = d3.select(this).attr("data-id");
    const text = d3.select(this).attr("data-text");
    const url = `${window.location.origin}${window.location.pathname}#${id}`;
    shareSel.select(".share-url input").property("value", url);
    shareSel.select(".share-title span").text(text);
    shareSel.classed("is-open", true);
  });
}

/**
 * Initializes the sidebar menu toggle.
 */
function createMenu() {
  const sidebar = d3.select(".sidebar");
  const button = d3.select("header .button-menu");

  button.on("click", () => {
    const isOpen = sidebar.classed("is-open");
    sidebar.classed("is-open", !isOpen);
  });

  d3.selectAll(".sidebar a").on("click", () => {
    sidebar.classed("is-open", false);
  });
}

/**
 * Initializes print listeners.
 * Ensures `<details>` elements are expanded when printing and collapsed after.
 */
function createPrint() {
  window.addEventListener("beforeprint", () => {
    document.querySelectorAll("details:not([open])").forEach((el) => {
      el.setAttribute("open", "");
      el.dataset.wasClosed = "true";
    });
  });

  window.addEventListener("afterprint", () => {
    document.querySelectorAll("details[data-was-closed]").forEach((el) => {
      el.removeAttribute("open");
      delete el.dataset.wasClosed;
    });
  });
}

/**
 * Initializes toggle inputs to switch between Topic and Opinion views.
 */
function createToggle() {
  const toggleInputs = document.querySelectorAll('input[name="toggleView"]');
  toggleInputs.forEach((input) => {
    input.addEventListener("change", (e) => {
      const value = e.target.value;
      if (value === "topics") createTopicChart();
      else if (value === "opinions") createOpinionChart();
    });
  });
}

// Application entry point: initialize all components and render the default view.
(() => {
  if (OVERVIEW_CHART_TYPE === "toggle") createToggle();

  if (OVERVIEW_CHART_TYPE === "opinions") createOpinionChart();
  else createTopicChart();
  createDonutCharts();
  createQuotesModal();
  createShare();
  createMenu();
  createPrint();

  const warningSel = d3.select(".warning");
  if (warningSel)
    setTimeout(() => {
      warningSel
        .transition()
        .duration(1000)
        .style("opacity", 0)
        .on("end", () => {
          warningSel.remove();
        });
    }, 2000);
})();
